### ISSUE TITLE
 npm' packages installed to global that couldn't find them.

### ISSUE THREAD

**Issue by IvanWei** [fisherman/nvm#3]
bower installed to global, fish known bower. When I restart fish that didn't know bower.

**Comment by brj** [comment]
@IvanWei Hi! I can't help you with this plugin so you'll need to talk to @FabioAntunes 

In the meantime, check out [fnm](https://github.com/fisherman/fnm) or [verman](https://github.com/fisherman/verman) which I maintain and are known to work with global modules.

**Comment by FabioAntunes** [comment]
@IvanWei nvm isn't being sourced on shell init, so unless you run nvm or npm first on your terminal, bower won't be recognized.

You could create a `bower.fish` in your functions folder inside `~/.config/fish` and then paste this:

function bower -d "Package manager"
  __nvm_run "bower" $argv
end

But as @brj said, try  [fnm](https://github.com/fisherman/fnm) or [verman](https://github.com/fisherman/verman) they are pure fish version managers

**Comment by IvanWei** [comment]
@FabioAntunes Thank you! 😄 

I know this idea, but it isn't convenient.
if many packages installed to global that need create more fish files.

**Comment by FabioAntunes** [comment]
@IvanWei If you really want to be able to run global packages you can source nvm on shell init, but be prepared to see a delay of some seconds. You can read more about that in this issue https://github.com/fisherman/nvm/issues/2
